# Generated by Django 6.0 on 2026-01-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_tablette_active_tablette_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablerestaurant',
            name='utilisateur',
        ),
    ]
