# Generated by Django 6.0 on 2026-01-05 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_tablerestaurant_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='items',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='user',
        ),
        migrations.RemoveField(
            model_name='panieritem',
            name='user',
        ),
        migrations.AddField(
            model_name='panieritem',
            name='tablette',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.tablette'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='tablette',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.tablette'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablerestaurant',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tablette',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'tablette'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CommandeItems',
        ),
    ]
