# Generated by Django 6.0 on 2026-02-02 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_update_commande_and_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode',
            field=models.CharField(choices=[('cash', 'Espèces')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='panieritem',
            name='tablette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion.tablette'),
        ),
    ]
