# Generated by Django 6.0 on 2026-02-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='quantite_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
