# Generated by Django 6.0 on 2026-02-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_commande_comptable_commande_serveur'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablette',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
