# Generated by Django 6.0 on 2026-02-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_tablette_is_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caisse',
            options={'verbose_name_plural': 'Caisse'},
        ),
    ]
