# Generated by Django 6.0 on 2026-02-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_tablette_qr_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablette',
            name='qr_password',
            field=models.CharField(blank=True, help_text='Mot de passe en clair pour les QR Codes', max_length=128, null=True),
        ),
    ]
